/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QrRouteImport } from './routes/qr'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FacultyRouteImport } from './routes/_faculty'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacultySalaryRouteImport } from './routes/_faculty/salary'
import { Route as FacultyPayslipRouteImport } from './routes/_faculty/payslip'
import { Route as FacultyBreakdownRouteImport } from './routes/_faculty/breakdown'
import { Route as FacultyAttendanceRouteImport } from './routes/_faculty/attendance'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedFacultyRouteImport } from './routes/_authenticated/faculty'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdmissionsAddTeacherRouteImport } from './routes/_authenticated/admissions/add-teacher'
import { Route as AuthenticatedAdmissionsAddStudentRouteImport } from './routes/_authenticated/admissions/add-student'
import { Route as AuthenticatedAdmissionsEditTeacherIdRouteImport } from './routes/_authenticated/admissions/edit-teacher.$id'
import { Route as AuthenticatedAdmissionsEditStudentIdRouteImport } from './routes/_authenticated/admissions/edit-student.$id'

const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/_faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySalaryRoute = FacultySalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyPayslipRoute = FacultyPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyBreakdownRoute = FacultyBreakdownRouteImport.update({
  id: '/breakdown',
  path: '/breakdown',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyAttendanceRoute = FacultyAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => FacultyRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacultyRoute = AuthenticatedFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdmissionsAddTeacherRoute =
  AuthenticatedAdmissionsAddTeacherRouteImport.update({
    id: '/admissions/add-teacher',
    path: '/admissions/add-teacher',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionsAddStudentRoute =
  AuthenticatedAdmissionsAddStudentRouteImport.update({
    id: '/admissions/add-student',
    path: '/admissions/add-student',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionsEditTeacherIdRoute =
  AuthenticatedAdmissionsEditTeacherIdRouteImport.update({
    id: '/admissions/edit-teacher/$id',
    path: '/admissions/edit-teacher/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionsEditStudentIdRoute =
  AuthenticatedAdmissionsEditStudentIdRouteImport.update({
    id: '/admissions/edit-student/$id',
    path: '/admissions/edit-student/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/qr': typeof QrRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/faculty': typeof AuthenticatedFacultyRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/attendance': typeof FacultyAttendanceRoute
  '/breakdown': typeof FacultyBreakdownRoute
  '/payslip': typeof FacultyPayslipRoute
  '/salary': typeof FacultySalaryRoute
  '/admissions/add-student': typeof AuthenticatedAdmissionsAddStudentRoute
  '/admissions/add-teacher': typeof AuthenticatedAdmissionsAddTeacherRoute
  '/admissions/edit-student/$id': typeof AuthenticatedAdmissionsEditStudentIdRoute
  '/admissions/edit-teacher/$id': typeof AuthenticatedAdmissionsEditTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/qr': typeof QrRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/faculty': typeof AuthenticatedFacultyRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/attendance': typeof FacultyAttendanceRoute
  '/breakdown': typeof FacultyBreakdownRoute
  '/payslip': typeof FacultyPayslipRoute
  '/salary': typeof FacultySalaryRoute
  '/admissions/add-student': typeof AuthenticatedAdmissionsAddStudentRoute
  '/admissions/add-teacher': typeof AuthenticatedAdmissionsAddTeacherRoute
  '/admissions/edit-student/$id': typeof AuthenticatedAdmissionsEditStudentIdRoute
  '/admissions/edit-teacher/$id': typeof AuthenticatedAdmissionsEditTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_faculty': typeof FacultyRouteWithChildren
  '/auth': typeof AuthRoute
  '/qr': typeof QrRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/faculty': typeof AuthenticatedFacultyRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_faculty/attendance': typeof FacultyAttendanceRoute
  '/_faculty/breakdown': typeof FacultyBreakdownRoute
  '/_faculty/payslip': typeof FacultyPayslipRoute
  '/_faculty/salary': typeof FacultySalaryRoute
  '/_authenticated/admissions/add-student': typeof AuthenticatedAdmissionsAddStudentRoute
  '/_authenticated/admissions/add-teacher': typeof AuthenticatedAdmissionsAddTeacherRoute
  '/_authenticated/admissions/edit-student/$id': typeof AuthenticatedAdmissionsEditStudentIdRoute
  '/_authenticated/admissions/edit-teacher/$id': typeof AuthenticatedAdmissionsEditTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/qr'
    | '/dashboard'
    | '/expenses'
    | '/faculty'
    | '/revenue'
    | '/students'
    | '/attendance'
    | '/breakdown'
    | '/payslip'
    | '/salary'
    | '/admissions/add-student'
    | '/admissions/add-teacher'
    | '/admissions/edit-student/$id'
    | '/admissions/edit-teacher/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/qr'
    | '/dashboard'
    | '/expenses'
    | '/faculty'
    | '/revenue'
    | '/students'
    | '/attendance'
    | '/breakdown'
    | '/payslip'
    | '/salary'
    | '/admissions/add-student'
    | '/admissions/add-teacher'
    | '/admissions/edit-student/$id'
    | '/admissions/edit-teacher/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_faculty'
    | '/auth'
    | '/qr'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/faculty'
    | '/_authenticated/revenue'
    | '/_authenticated/students'
    | '/_faculty/attendance'
    | '/_faculty/breakdown'
    | '/_faculty/payslip'
    | '/_faculty/salary'
    | '/_authenticated/admissions/add-student'
    | '/_authenticated/admissions/add-teacher'
    | '/_authenticated/admissions/edit-student/$id'
    | '/_authenticated/admissions/edit-teacher/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FacultyRoute: typeof FacultyRouteWithChildren
  AuthRoute: typeof AuthRoute
  QrRoute: typeof QrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty': {
      id: '/_faculty'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/salary': {
      id: '/_faculty/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof FacultySalaryRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/payslip': {
      id: '/_faculty/payslip'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof FacultyPayslipRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/breakdown': {
      id: '/_faculty/breakdown'
      path: '/breakdown'
      fullPath: '/breakdown'
      preLoaderRoute: typeof FacultyBreakdownRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/attendance': {
      id: '/_faculty/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof FacultyAttendanceRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faculty': {
      id: '/_authenticated/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AuthenticatedFacultyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admissions/add-teacher': {
      id: '/_authenticated/admissions/add-teacher'
      path: '/admissions/add-teacher'
      fullPath: '/admissions/add-teacher'
      preLoaderRoute: typeof AuthenticatedAdmissionsAddTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admissions/add-student': {
      id: '/_authenticated/admissions/add-student'
      path: '/admissions/add-student'
      fullPath: '/admissions/add-student'
      preLoaderRoute: typeof AuthenticatedAdmissionsAddStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admissions/edit-teacher/$id': {
      id: '/_authenticated/admissions/edit-teacher/$id'
      path: '/admissions/edit-teacher/$id'
      fullPath: '/admissions/edit-teacher/$id'
      preLoaderRoute: typeof AuthenticatedAdmissionsEditTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admissions/edit-student/$id': {
      id: '/_authenticated/admissions/edit-student/$id'
      path: '/admissions/edit-student/$id'
      fullPath: '/admissions/edit-student/$id'
      preLoaderRoute: typeof AuthenticatedAdmissionsEditStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFacultyRoute: typeof AuthenticatedFacultyRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedAdmissionsAddStudentRoute: typeof AuthenticatedAdmissionsAddStudentRoute
  AuthenticatedAdmissionsAddTeacherRoute: typeof AuthenticatedAdmissionsAddTeacherRoute
  AuthenticatedAdmissionsEditStudentIdRoute: typeof AuthenticatedAdmissionsEditStudentIdRoute
  AuthenticatedAdmissionsEditTeacherIdRoute: typeof AuthenticatedAdmissionsEditTeacherIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFacultyRoute: AuthenticatedFacultyRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedAdmissionsAddStudentRoute:
    AuthenticatedAdmissionsAddStudentRoute,
  AuthenticatedAdmissionsAddTeacherRoute:
    AuthenticatedAdmissionsAddTeacherRoute,
  AuthenticatedAdmissionsEditStudentIdRoute:
    AuthenticatedAdmissionsEditStudentIdRoute,
  AuthenticatedAdmissionsEditTeacherIdRoute:
    AuthenticatedAdmissionsEditTeacherIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface FacultyRouteChildren {
  FacultyAttendanceRoute: typeof FacultyAttendanceRoute
  FacultyBreakdownRoute: typeof FacultyBreakdownRoute
  FacultyPayslipRoute: typeof FacultyPayslipRoute
  FacultySalaryRoute: typeof FacultySalaryRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyAttendanceRoute: FacultyAttendanceRoute,
  FacultyBreakdownRoute: FacultyBreakdownRoute,
  FacultyPayslipRoute: FacultyPayslipRoute,
  FacultySalaryRoute: FacultySalaryRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FacultyRoute: FacultyRouteWithChildren,
  AuthRoute: AuthRoute,
  QrRoute: QrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
